### ISSUE TITLE
Kotlin 2.x Support

### ISSUE THREAD

**Issue by Shabinder** [jisungbin/ComposeInvestigator#191]
Error Log:
```
e: There are some plugins incompatible with language version 2.0:
  land.sungbin.composeinvestigator.compiler.ComposeInvestigatorPluginRegistrar
Please use language version 1.9 or below
```

**Comment by jisungbin** [comment]
Hi! Thanks for sharing your issue.

I am currently working on K2 (Kotlin 2.x) and it is not released yet. I think it will be released within this month.

**Comment by Shabinder** [comment]
Thanks for the update.

**Comment by jisungbin** [comment]
https://github.com/jisungbin/ComposeInvestigator/pull/172
